[package]
name = "fer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
GSL = "6.0"
clap = { version = "4.3.12", features = ["derive"]} 
csv = "1.2.2"
rand = "0.8.5"
nalgebra = "0.32.3"

